package astutil

import (
	"context"
	"errors"
	"go/ast"
	"go/token"
	"strings"

	"1pkg/gopium"

	"golang.org/x/sync/errgroup"
)

// filternote helps to filter relevant
// docs and comments from ast.TypeSpec,
// filters only comments inside
// relevant structs and autogenerated comments
func filternote(
	ctx context.Context,
	pkg *ast.Package,
	loc gopium.Locator,
	hsts HierarchyStructs,
	fsets map[string]*token.FileSet,
) (*ast.Package, error) {
	// prepare structs boundaries
	type boundary struct{ Pos, End token.Pos }
	boundaries := make([]boundary, 0, len(hsts))
	// collect structs boundaries
	if _, err := walkPkg(
		ctx,
		pkg,
		hierarchy(loc, hsts),
		func(ts *ast.TypeSpec, st gopium.Struct) error {
			// check that we are working with ast.StructType
			tts, ok := ts.Type.(*ast.StructType)
			if !ok {
				return errors.New("boundaries could only be collected from ast.StructType")
			}
			// append boundaries to list
			boundaries = append(boundaries, boundary{
				Pos: tts.Fields.Opening,
				End: tts.Fields.Closing,
			})
			return nil
		},
	); err != nil {
		return nil, err
	}
	// create sync error group
	// with cancelation context
	group, gctx := errgroup.WithContext(ctx)
	// go through package files
	for _, file := range pkg.Files {
		file := file
		group.Go(func() error {
			// go through all file comments
			for _, comments := range file.Comments {
				// manage context actions
				// in case of cancelation
				// stop execution
				select {
				case <-gctx.Done():
					return gctx.Err()
				default:
				}
				// prepare comment list
				clist := make([]*ast.Comment, 0, len(comments.List))
				// go through comment list
			loop:
				for _, c := range comments.List {
					// in case comment has autogenerated prefix skip it
					if strings.Contains(c.Text, gopium.STAMP) {
						continue loop
					}
					// in case comment is inside boundaries skip it
					for _, b := range boundaries {
						if b.Pos <= c.Slash && c.Slash <= b.End {
							continue loop
						}
					}
					// append comment to list
					clist = append(clist, c)
				}
				// update comment list
				comments.List = clist
			}
			return nil
		})
	}
	return pkg, group.Wait()
}
