name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        go-version: [1.22.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: setup
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: go build ./...
